name: Docker

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ new-commit-from-SVF ]

jobs:
  docker-image:
    if: github.repository == 'SVF-tools/Software-Analysis-Studio'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWD}}

      - name: Set up QEMU (Support ARM64)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push x86 and ARM64 images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{secrets.DOCKER_USER}}/software-analysis-studio:latest
            ${{secrets.DOCKER_USER}}/software-analysis-studio:latest-arm64
